units:
  $default_width: cx
  $default_height: cy
points:
  key:
    autobind: 0
  zones:
    alphas:
      anchor:
        shift: [150, -150]
      key:
        spread: cx
        padding: cy
      columns:
        pinky:
          key:
            splay: 15
          rows:
            bottom:
              bind: [1, 0, 0, 0]
            home:
              bind: [1, 10, 0, 0]
            top:
              bind: [0, 7, 0, 0]
        ring:
          key:
            splay: -10
            stagger: 17
            spread: cx + 2
          rows:
            bottom:
              bind: [0, 22, 0, 0]
            home:
              bind: [1, 4, 0, 0]
            top:
              bind: [0, 5, 0, 0]
        middle:
          key:
            splay: -5
            stagger: 6
            spread: cx + 1.5
          rows:
            bottom:
              bind: [0, 0, 0, 0]
            home:
              bind: [0, 0, 0, 0]
            top:
              bind: [0, 0, 0, 0]
        index:
          key:
            splay: -5
            stagger: -6
            spread: cx + 1
          rows:
            bottom:
              bind: [0, 0, 0, 2]
            home:
              bind: [0, 0, 0, 4]
            top:
              bind: [0, 0, 0, 5]
        inner:
          key:
            stagger: -1
          rows:
            bottom:
              bind: [0, 20, 8, 1]
            home:
              bind: [0, 28, 0, 1]
            top:
              bind: [1, 0, 1, 1]
      rows:
        bottom:
        home:
          padding: 17
        top:
          padding: 17
    thumb:
      anchor:
        ref: alphas_inner_bottom
        shift: [-9, -22]
      columns:
        outer:
          key:
            splay: -5
            rotate: 10
            bind: [7, 1, 0, 0]
            column_net: B3
        middle:
          key:
            splay: -10
            shift: [2.1, 0.3]
            bind: [5, 1, 0, 7]
            column_net: B2
        inner:
          key:
            splay: -20
            shift: [4.7, -1.8]
            bind: [3.7, 0, 0, 7]
            column_net: B6
outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      asym: left
      size: [cx+2, cy+1]
      corner: 1
  first:
    - what: outline
      name: raw
      fillet: 3
pcbs:
  endruil:
    template: kicad8
    outlines:
      main:
        outline: first
    footprints:
      keys:
        what: custom/switch_choc_v1_v2
        where: true
        params:
          include_keycap: true
          keycap_width: 17.5
          keycap_height: 16.5
          choc_v2_support: false
          reversible: true
          solder: true
          from: "{{column_net}}"
          to: "GND"
      controller:
        what: custom/elite-c
        params:
          reversable: true
          reversable_pins: 5
        where:
          ref: alphas_inner_home
          shift: [20,-10.5]
          rotate: 0
      trrs:
        what: trrs
        params:
          reverse: true
          symmetric: true
          A: ""
          B: ""
          C: ""
          D: ""
        where:
          ref: alphas_inner_home
          shift: [35.7,5]
          rotate: 0


